---
title: "No emergence analysis"
output: html_document
date: "2024-05-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Loading packages
```{r}
library(tidyverse)
library(car)
library(ggeffects)
```

# Loading in data
```{r}
Fly_data <- read_csv('Fly counts.csv')
```

# Fitting GLM - logisitic
```{r}
Fly_data$G0 <- factor(Fly_data$G0)

NoEmergence_G0 <- glm(Zero_emergence ~ G0, data=Fly_data,
                       family=binomial(link="logit"))

NoEmergence_G1 <- glm(Zero_emergence ~ G1, data=Fly_data,
                       family=binomial(link="logit"))

NoEmergence_NoInt <- glm(Zero_emergence ~ G1+G0, data=Fly_data,
                       family=binomial(link="logit"))

NoEmergence_Int <- glm(Zero_emergence ~ G0*G1, data=Fly_data,
                       family=binomial(link="logit"))

AIC(NoEmergence_G0, NoEmergence_G1, NoEmergence_NoInt, NoEmergence_Int)

Anova(NoEmergence_Int, test="F")
Anova(NoEmergence_NoInt, test="F")
```

# Model comparison table
```{r, echo=FALSE}
NoEmergence_models <- data.frame(
  Model = c('NoEmergence_G0', 
            'NoEmergence_G1',
            'NoEmergence_NoInt',
            'NoEmergence_Int'),
  Explanatory_variable = c('G0',
                           'G1',
                           'G1+G0',
                           'G1*G0'),
  Likelihood = round(c(logLik(NoEmergence_G0), 
                       logLik(NoEmergence_G1), 
                       logLik(NoEmergence_NoInt), 
                       logLik(NoEmergence_Int)), digits = 2),
  AIC = round(c(AIC(NoEmergence_G0), 
                AIC(NoEmergence_G1), 
                AIC(NoEmergence_NoInt), 
                AIC(NoEmergence_Int)), digits = 2))

NoEmergence_models

write.csv(NoEmergence_models, "NoEmergence_models.csv", row.names = FALSE)
```

# Plotting
```{r, echo=FALSE}
predicted_noemergence <- ggpredict(NoEmergence_NoInt, c("G1", "G0"))

ggplot() +
    geom_line(data = predicted_noemergence, aes(x = x, y = predicted, colour=group)) +
    geom_ribbon(data = predicted_noemergence, 
              aes(x = x, ymin = conf.low, ymax = conf.high, fill=group), alpha = 0.2) + 
    geom_point(data = Fly_data, aes(x = G1, y = Zero_emergence, 
               color=as.factor(G0), shape = as.factor(G0)), alpha=0.6, size=1.2, 
               position = position_jitterdodge(jitter.width = 0.8, 
                                               dodge.width=0.95, jitter.height=0.01)) +
    scale_x_continuous(breaks = seq(19, 27, by = 2)) +
    scale_color_manual(values = c("#0072B2", "#009E73", "#D55E00")) +
    scale_fill_manual(values = c("#0072B2", "#009E73", "#D55E00")) +
    scale_shape_manual(values = c(15, 16, 17), name="G0 Temperature (째C)") +
    labs(x = "G1 Temperature (째C)", 
         y = "Probability of vial with no emergence",
         title = "Probability of vial with no emergence",
         colour="G0 Temperature (째C)",
         fill="G0 Temperature (째C)") +
    theme_bw(base_size=12) +
    theme(text = element_text(size = 9))
```


# Link to single founder vials
```{r}
zero_emergence_model <- glm(Zero_emergence ~ G0_deaths+(G1+G0),
              data=Fly_data,
              family=binomial)

Anova(zero_emergence_model,test="F")
```











