---
title: "Simulation model"
output: html_document
date: "2024-05-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading packages
```{r}
library(tidyverse)
```


# Precursers and parameters
```{r}
set.seed(1)

## time = generations 

params<- list(
  ## fly params
  'topt'= 26.313093,  ## from all together fit 
  'rmax' =  38.854392, ## from all together fit 
  'fly_a' = 3.052021, ## from all together fit
  'ctmax' = 30, 
  'fly_K' = 100000,     #setting large carrying capacity 
  'fly_fail'= 20,
  ## wasp params
  'wasp_a' = 0.00026,
  'wasp_h' = 0.01, ## set like this because 1/100 = max number of eggs
  'wasp_k' = 0.65 
)

setup<- list( 'Av_temp' = 24, 
              'MaxTemp' = 29, 
              'burnin' = 500,  #burn-in time
              'CC_time' = 2000, #climate change time - 2000 gens = so to around year 2100 - at worst climate change scenarios could be up to 4.7 degrees of warming above baseline by 2100 (IPCC report)
              'temp_sd' = 1,   #standard deviation of temp - sd of Australian data summer av mid temps = 1.1
              'Start_flies' = 10000, 
              'Start_wasps' = 100, 
              'threshold' = 1, #below 1 individual, deemed extinct
              'AutoCorrelated' = FALSE,
              'autocorrelation' = 0.8, #ac of Australian av mid temp = 0.879
              'transgenerational_fly'= TRUE,
              'transgenerational_wasp' = TRUE)  

L <- setup$burnin + setup$CC_time  #overall time

### For testing purposes only:
## Env_vec is a vector representing environmental temps over time with a burn-in period followed by a change in temperature over the climate change time

Env_vec <- c( rep(setup$Av_temp, 
                  setup$burnin), 
              seq( from = setup$Av_temp,
                   to = setup$MaxTemp, 
                   length.out = setup$CC_time )) + rnorm(L, 
                                                         mean = 0,
                                                         sd = setup$temp_sd)

Env_vec[ Env_vec>(params$ctmax -0.1) ] <- (params$ctmax-0.1) #stop going above ctmax



plot(Env_vec, xlab="Time (generations)", ylab="Temperature (°C)")
abline(h=params$ctmax)
mtext("Simulation model environmental conditions", side = 3, line = 1, cex = 1)
```


## Fly interpolation functions
```{r}
load('Fly TPC models/NB_AllG0Seperate_fit')

topt19  = 28.3656893
topt23 =  28.3467465
topt27 =  29.0000000
rmax19 =  46.1107868 
rmax23 =  71.3059568 
rmax27 =  20.4986572 
a19   = 4.2125259  
a23   = 3.6526915 
a27   = 3.2156789 

cTmax = 30

## Rmax

Rmax_interp<- Vectorize(function(G0){
  Rmax<- ifelse( G0<23, rmax19 + ((G0-19)/4) * (rmax23 - rmax19),
                 rmax23 + ((G0-23)/4) * (rmax27 - rmax23))
  ifelse( Rmax< 0.1, return(0.1), return(Rmax))
})

## Topt

Topt_interp<- Vectorize(function(G0){
  
  Topt<-  ifelse( G0<23, topt19 + ((G0-19)/4) * (topt23 - topt19),
                  topt23 + ((G0-23)/4) * (topt27 - topt23)) 
  
  ifelse( Topt>(cTmax-0.1) , return(cTmax-0.1), return(Topt))
})

## A

a_interp<- Vectorize(function(G0){
  ifelse( G0<23, a19 + ((G0-19)/4) * (a23 - a19),
          a23 + ((G0-23)/4) * (a27 - a23))
})

## checking it works
G0_seq <- seq( from = 19, to = 30, by =0.1)
par(mfrow=c(1,3), outer = TRUE, cex.lab = 1.5, mar = c(5, 5, 4, 2) + 0.1)
plot(Topt_interp(G0_seq)~G0_seq, xlab = "G0 Temperature (°C)", ylab = "Topt", xaxt = "n")
points(19, 28.7833042, col="red", pch = 19)
points(23, 28.3088035, col="red", pch = 19)
points(27, 29.0000000, col="red", pch = 19)
new_x_ticks <- c(19, 21, 23, 25, 27)
new_x_labels <- c(19, 21, 23, 25, 27)
axis(side = 1, at = new_x_ticks, labels = new_x_labels)

plot(Rmax_interp(G0_seq)~G0_seq, xlab = "G0 Temperature (°C)", ylab = "Rmax", xaxt = "n")
points(19, 45.4438706, col="red", pch = 19)
points(23, 70.8444017, col="red", pch = 19)
points(27, 20.9152802, col="red", pch = 19)
new_x_ticks <- c(19, 21, 23, 25, 27)
new_x_labels <- c(19, 21, 23, 25, 27)
axis(side = 1, at = new_x_ticks, labels = new_x_labels)

plot(a_interp(G0_seq)~G0_seq, xlab = "G0 Temperature (°C)", ylab = "a", xaxt = "n")
points(19, 4.4715369, col="red", pch = 19)
points(23, 3.6106929, col="red", pch = 19)
points(27, 3.2001349, col="red", pch = 19)
new_x_ticks <- c(19, 21, 23, 25, 27)
new_x_labels <- c(19, 21, 23, 25, 27)
axis(side = 1, at = new_x_ticks, labels = new_x_labels)

mtext("Fly Interpolation Functions", side = 3, line = -2, outer = TRUE, cex = 1.2)
```


# Function to calculate Environmental Performance Curve
```{r}
EPC_trans = function(G1_temp, G0_temp, cTmax){
  Rmax<- Rmax_interp(G0_temp)
  Topt<- Topt_interp(G0_temp)
  a   <- a_interp(   G0_temp)
  R =  Rmax* ifelse(G1_temp < Topt,
                    exp(-((G1_temp - Topt)/(2 * a))^2), 
                    1 - ((G1_temp - Topt)/(Topt - cTmax))^2)
  return(R)
}
```

# Plotting EPC
```{r}
library(viridis)
color_palette <- viridis_pal(option="C")(12)

library(RColorBrewer)
library(wesanderson)
color_palette1 <- wes_palette("Zissou1", 12, type = "continuous")

expand_grid(G0 = seq(from = 19, to = 30, by = 1),
            G1 = seq(from = 19, to = 30, by = 0.01 )) %>%
  mutate( Rmax = Rmax_interp(G0),
          Topt = Topt_interp(G0),
          a = a_interp(G0), 
          R_predict = EPC_trans( G1_temp = G1, G0, cTmax=30)) %>%
  mutate(R_predict = ifelse(R_predict<0, 0, R_predict )) %>%
  ggplot(aes(x = G1, y = R_predict, col = factor(G0))) +
  geom_line() +
  labs(title="Fly Environmental Performance Curve",
    x="G1 Temperature (°C)", y="Population growth rate",
    colour="G0 Temperature (°C)") +
  scale_color_manual(values = color_palette1) +
  theme_bw()
```


# Function to make autocorrelate numbers
```{R}
Make_AC_data<- function(N, sd, AC){
  numbers <- rep(NA, N)
  numbers[1] <- rnorm(1,0)  # Mean=0
  
  for(i in 2:N) { 
    numbers[i]<-numbers[i-1]* AC + rnorm(1,0)
  }
return(  scale(numbers)  *sd)
}

## testing
Make_AC_data(2000, sd=3.567, AC=0.8) -> X
X%>% plot
mean(X)
sd(X)
```


# Function to predict wasp from G0 and G1
```{r}
load('WaspModel') ##waspglm2_poly
load('WaspModel_NoG0') ##waspglm2_no_G0
```


# Main Model Function
```{r}

TestExtinctionPoint <- function(seed, params, setup, PLOT=TRUE){
  
  set.seed(seed)
  
  Density_m <- as.data.frame(matrix(NA, ncol = 8, nrow = L)) 
  colnames(Density_m)<- c('Flies', 'Wasps', 'r', 'temp', 'PropFliesSurv', 'w_att_temp_WOTRANS','w_att_tempWithTRANS','WaspRiskFactor')
  Density_m$Flies[1] <- setup$Start_flies
  Density_m$Wasps[1] <- setup$Start_wasps
  
  
  
  if(setup$AutoCorrelated == FALSE){
    Env_vec <- c( rep(setup$Av_temp, 
                      setup$burnin), 
                  seq( from = setup$Av_temp,
                       to = setup$MaxTemp, 
                       length.out = setup$CC_time )) + rnorm(L, 
                                                             mean = 0,
                                                             sd = setup$temp_sd)
  }else{
    
    
    Env_vec <- c( rep(setup$Av_temp, 
                      setup$burnin), 
                  seq( from = setup$Av_temp,
                       to = setup$MaxTemp, 
                       length.out = setup$CC_time )) + Make_AC_data(N = L,
                                                                    AC = setup$autocorrelation,
                                                                    sd = setup$temp_sd)
  }
  
  
  
  Env_vec[ Env_vec>(params$ctmax -0.1) ] <- (params$ctmax-0.1)
  
  ### Fly temperature dependence
  
  for( t in 2: L){
    
    Prev_Flies <- Density_m[t-1,1]
    Prev_Wasps <- Density_m[t-1,2]
    temp = Env_vec[t]
    G0_temp = Env_vec[t-1]
    
    #calculating growth rate of population based on parameters and environmental temp
    #with transgenerational effects and without    
    
    if(setup$transgenerational_fly){
      r <- EPC_trans(G1_temp = temp,
                     G0_temp = G0_temp,
                     cTmax = params$ctmax) 
    }else{
      r <- params$rmax* ifelse(temp < params$topt,
                               exp(-((temp -  params$topt)/
                                       (2 * params$fly_a))^2),
                               1 - ((temp -  params$topt)/
                                      ( params$topt -  params$ctmax))^2)
    }
    
    ### Wasp temperature dependence
    ## Wasp model fitted from data gives us proportion of wasps attacked (ranging from 0-1)
    ## Most direct way to build that is just to scale the 'wasp_a' rate parameter by this
    ## not perfect, but should capture response dynamics
    # 
    # if(setup$transgenerational_wasp){
    #   w_att_temp = params$wasp_a * predict(waspglm2_poly,
    #                                        newdata = data.frame(G0 = G0_temp,
    #                                                             G1 = temp) ,
    #                                        type='response' )
    #   #with transgenerational effects and without  
    # }else{
    #   w_att_temp = params$wasp_a * predict(waspglm2_noG0,
    #                                        newdata = data.frame(G1 = temp) ,
    #                                        type='response' ) 
    #   ## alternative no-trans effect
    #         # w_att_temp = params$wasp_a * predict(waspglm2_poly,
    #         #                                newdata =data.frame(G0 = temp,
    #         #                                                     G1 = temp),
    #         #                                type='response' ) 
    #   }
    # 
    
    
    w_att_temp_WITHTRANS = params$wasp_a * predict(waspglm2_poly,
                                                   newdata = data.frame(G0 = G0_temp,
                                                                        G1 = temp) ,
                                                   type='response' )
    
    w_att_tempWITHOUTTRANS = params$wasp_a * predict(waspglm2_noG0,
                                                     newdata = data.frame(G1 = temp) ,
                                                     type='response' ) 
    #with transgenerational effects and without  
    
    if(setup$transgenerational_wasp){
      w_att_temp = w_att_temp_WITHTRANS
    }else{
      w_att_temp = w_att_tempWITHOUTTRANS
    }
    
    # Calculating projected fly population at next time step
    #based on growth rate, previous fly density and carrying capacity
    Next_Flies_potential <- r * (1/params$fly_fail)*Prev_Flies * (1 - (Prev_Flies / params$fly_K )) 
    
    
    # PropFliesSurv = How many flies survive

    w_k<- params$wasp_k
    WaspRiskFactor = (1+((w_att_temp*Prev_Wasps)/
                        (w_k*(1 + w_att_temp*params$wasp_h*Next_Flies_potential)) ) )^w_k    
    ## from page 50 (Hassell)
    
    PropFliesSurv = 1/WaspRiskFactor
    
    Next_Flies <- Next_Flies_potential*(PropFliesSurv)
    Next_Wasps <- Next_Flies_potential*(1-PropFliesSurv) +10
    
    Density_m$PropFliesSurv[t] <- PropFliesSurv
    Density_m$r[t] <- r
    Density_m$temp[t] <- temp
    Density_m$Flies[t] <- Next_Flies  
    Density_m$Wasps[t] <- Next_Wasps 
    Density_m$w_att_temp_WOTRANS[t] <- w_att_tempWITHOUTTRANS
    Density_m$w_att_tempWithTRANS[t] <- w_att_temp_WITHTRANS
    Density_m$WaspRiskFactor[t] <- WaspRiskFactor
    
  }
  
  if(PLOT){
      par(mfrow = c(2,2))
  plot(Density_m$Flies, main = 'fly') #plot fly densities
  plot(Density_m$Wasps, main = 'wasp') #plot wasp densities
  plot(Env_vec, main = 'temp')
  abline(h=params$ctmax)
  }

  
  print(Density_m[1:50,])
  if( all( Density_m$Flies[201:nrow(Density_m)] > setup$threshold)){return(NA)}
  return(which.max(Density_m$Flies[201:nrow(Density_m)] < setup$threshold)+200)
}

```


# Simulation runs
```{R}
NUM_REPS = 100
```

# No autocorrelation
```{r}
set.seed(1)

setup$AutoCorrelated<-FALSE


setup$transgenerational_fly<-TRUE
setup$transgenerational_wasp<-TRUE
Extinctions_NoAuto_BothTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

setup$transgenerational_fly<-TRUE
setup$transgenerational_wasp<-FALSE
Extinctions_NoAuto_FlyTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

setup$transgenerational_fly<-FALSE
setup$transgenerational_wasp<-TRUE
Extinctions_NoAuto_WaspTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

setup$transgenerational_fly<-FALSE
setup$transgenerational_wasp<-FALSE
Extinctions_NoAuto_NoTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)


mean(Extinctions_NoAuto_BothTrans)
mean(Extinctions_NoAuto_FlyTrans)
mean(Extinctions_NoAuto_WaspTrans)
mean(Extinctions_NoAuto_NoTrans)
```

# With autocorrelation
```{r}
set.seed(1)

setup$AutoCorrelated<-TRUE


setup$transgenerational_fly<-TRUE
setup$transgenerational_wasp<-TRUE
Extinctions_Auto_BothTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

setup$transgenerational_fly<-TRUE
setup$transgenerational_wasp<-FALSE
Extinctions_Auto_FlyTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

setup$transgenerational_fly<-FALSE
setup$transgenerational_wasp<-TRUE
Extinctions_Auto_WaspTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

setup$transgenerational_fly<-FALSE
setup$transgenerational_wasp<-FALSE
Extinctions_Auto_NoTrans <- map_int(.x = 1:NUM_REPS, .f =  TestExtinctionPoint,
                       params = params, setup=setup, PLOT=FALSE)

mean(Extinctions_Auto_BothTrans)
mean(Extinctions_Auto_FlyTrans)
mean(Extinctions_Auto_WaspTrans)
mean(Extinctions_Auto_NoTrans)
```

# Combining
```{r}
data.frame(Extinctions_NoAuto_BothTrans,
           Extinctions_NoAuto_NoTrans ,
           Extinctions_Auto_BothTrans,
           Extinctions_Auto_NoTrans) %>%
  mutate(TrialID = 1:n()) %>%
  pivot_longer(cols= -TrialID,
               names_to = 'Name', values_to = 'Extinctions') %>%
  separate(Name, into = c('Ex', 'AC', 'TransGen')) -> LongFormExtData


LongFormExtData
```


# Geometric mean table of results
```{r}
library(psych)

modelling_results_2 <- matrix(
  c(geometric.mean(Extinctions_Auto_NoTrans), 
    geometric.mean(Extinctions_Auto_WaspTrans),
    geometric.mean(Extinctions_Auto_FlyTrans),
    geometric.mean(Extinctions_Auto_BothTrans), 
    geometric.mean(Extinctions_NoAuto_NoTrans), 
    geometric.mean(Extinctions_NoAuto_WaspTrans),
    geometric.mean(Extinctions_NoAuto_FlyTrans),
    geometric.mean(Extinctions_NoAuto_BothTrans), digits=2),
  nrow=4,
  ncol=2,
)

rownames(modelling_results_2) <- c("No transgenerational effects", "Wasp transgenerational effects",
                                 "Fly transgenerational effects", "Both transgenerational effects")
colnames(modelling_results_2) <- c("Autocorrelation", "No autocorrelation")

print(modelling_results_2)

write.csv(modelling_results_2, "Mean time to extinction (generations).csv")
```

